### ISSUE TITLE
user story , README.md

### ISSUE THREAD

**Issue by pbokor** [Moorgal/Safe-Plates#5]

**Comment by web3cryptoidea** [comment]
As a user I want to be able to choose the recipes excluding ingredients I am allergic or intolerant to. As a user I want to see what cuisine and diet my chosen recipe corresponds to. As a user I want to be able  to choose the restaurant in desired location that has similar cuisine and serves dishes related to the same diet.

**Comment by web3cryptoidea** [comment]
Our mission is to help people with food allergies and intolerances find recipes that cater to their unique dietary needs and preferences and discover restaurants that serve dishes in line with their preferred cuisine and diet.  

For individuals with food allergies and intolerances, every meal can feel like a lottery with unknown consequences. From light allergies to stomach discomfort and even the risk of anaphylactic shock, the dangers associated with consuming the wrong foods can be severe. This often causes a feeling of anxiety and fear when making food choices, both at home and when dining out.

Safe Plates addresses this problem by providing a solution app where users can easily filter recipes based on their specific dietary restrictions, ensuring that they only see options that are safe and suitable for them.  Safe Plates also helps users locate restaurants in their desired location that serve dishes related to their preferred cuisine and diet, so they can dine out with confidence.

With Safe Plates, individuals with food allergies and intolerances no longer have to feel like they are playing a dangerous game with their health every time they eat. They can enjoy delicious meals that cater to their unique needs, explore new cuisines, and experience the joys of dining out without any worries or concerns.
