### ISSUE TITLE
site interactions

### ISSUE THREAD

**Issue by pbokor** [Moorgal/Safe-Plates#8]

**Comment by web3cryptoidea** [comment]
1.  Input form for (fields names): 
- 1 main ingredient, 
- 2 cuisine (drop-down)
- 3 diet (drop-down)
- 4 allergies (drop-down) or check the existing list of allergies (preferable)
- 5 intolerances (= exclude Ingredients input field). 

2. Response
- Name of the recipe
- Picture
- Ingredients
- Cooking instructions

3. Another form : search location, name of cuisine / diet / name of the dish
4. Response: list of restaurants
